### ISSUE TITLE
TypeError: (intermediate value).flat is not a function

### ISSUE THREAD

**Issue by brycewray** [chromeos/static-site-scaffold-modules#16]
When attempting to use `eleventy-plugin-local-respimg`, I am getting the following console error, followed by failure of Eleventy to write most of the pages in my repo, which currently is private:

```
`TypeError` was thrown:
     TypeError: (intermediate value).flat is not a function
```

... followed by a path that leads to the plugin's `/lib/respimg.js:162:112`. Lines 161 through 163 are as follows:

```
              if (optimize) {
                await Promise.all((await Promise.all(await resizeAndOptimize(sizes, type, src, file, config))).flat().map(f => writeFile(f.dest, f.buff)));
              }
```

My config for the plugin in `.eleventy.js` is:

```
  eleventyConfig.addPlugin(pluginLocalRespImg, {
    folders: {
      source: 'src',
      output: '_site',      
    },
    images: {
      resize: {
        min: 300,
        max: 1500,
        step: 300,
      },
      gifToVideo: false,
      sizes: '100vw',
      lazy: true,
      additional: [
        'images/icons/**/*',
      ],
      watch: {
        src: 'images/**/*'
      },
      pngquant: {},
      mozjpeg: {},
      svgo: {},
      gifresize: {},
      webp: {},
      gifwebp: {},
    }
  })
```

Thanks in advance for any help you can provide about this; please let me know if you need additional information about the error I'm seeing.

**Comment by Snugug** [comment]
Hey! Thanks for using the module and for filing a bug! That line of code is usually related to problems with the images itself; can you please put together a test repo for me to check out, or write a failing test for the repo, that reproduces this error for me to look in to?

Thanks!

**Comment by brycewray** [comment]
@Snugug I have just made the following repo public so you can take a look:
https://github.com/brycewray/eleventy_solo
...and the branch you should check is called "unpacking" (I'm testing a non-webpack version of my site's current Eleventy/webpack repo). If you need more info, please advise, and thanks!

**Comment by brycewray** [comment]
@Snugug Any development on this? (Pardon the semi-intentional pun.) Thanks.

**Comment by Snugug** [comment]
Thanks for the repo! I'll look into this this week.

**Comment by RickTheHat** [comment]
_(intermediate value).flat is not a function_

I'm getting this same error when Netlify tries to deploy my site ... it does work locally as expected.

5:05:35 PM: 2020-05-09T22:05:35.287Z Eleventy:EleventyErrorHandler Having trouble writing template: dist/posts/index.html
5:05:35 PM: `TemplateWriterWriteError` was thrown
5:05:35 PM: 2020-05-09T22:05:35.287Z Eleventy:EleventyErrorHandler (error stack): TemplateWriterWriteError: Having trouble writing template: dist/posts/index.html
5:05:35 PM:     at /opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:181:15
5:05:35 PM: 2020-05-09T22:05:35.287Z Eleventy:EleventyErrorHandler (intermediate value).flat is not a function
5:05:35 PM: `TypeError` was thrown:

**Comment by RickTheHat** [comment]
Not an issue with your plugin but rather the node version Netlify uses when it deployments your site. In Netlify add an environment variable named "NODE_VERSION" and set to at least 12.16.1 as per this article i.e. https://community.netlify.com/t/npm-run-generate-runs-locally-but-not-on-netlify/10813/2?u=rickthehat

**Comment by brycewray** [comment]
Thanks for the info, @RickTheHat! Works in my local testing with Node 14.2.0. After I revise my Markdown-based `<img>` content, will make a quick test in Netlify (where I've already adjusted the env var as per that link) and, if it works as I now feel it will, will be closing this issue.

**Comment by brycewray** [comment]
Closing as mentioned earlier.
